cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from shop.views import detalleProducto
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^other', include('shop.urls', namespace='shop')),
    url(r'^tienda$', views.Tienda, name='tienda'),
    url(r'^detalleProducto', detalleProducto, name='detalleProducto'),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]


urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name= 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(required=False,choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

    cantidadProducto = forms.CharField(required=False, widget= forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=int(cd['cantidadProducto']),
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "basetienda.html" %}
{% load static %}

{% block pageTitle %}Carrito de compras{% endblock %}
{% block references %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css'%}" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/single_styles.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/cart_responsive.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/base.css'%}">
{% endblock %}

{% block contenidoPrincipal %}

    <h1>Tu carrito de compras</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Eliminar</th>
                <th>Precio Unitario</th>
                <th>Precio total</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Eliminar</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'tienda' %}" class="button light">Continuar comprando</a>
        <a href="{% url "orders:order_create" %}" class="button">Realizar pago</a>
    </p>
{% endblock %}