cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from shop.views import detalleProducto
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage, name='home'),
    url(r'^other', include('shop.urls', namespace='shop')),
    url(r'^tienda$', views.Tienda, name='tienda'),
    url(r'^detalleProducto', detalleProducto, name='detalleProducto'),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]


urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/basetienda.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
<title>{% block pageTitle %}CoprenLM{% endblock %}</title>
<link rel="icon" href="{% static 'images/logo8.jpeg'%}">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Tienda en línea">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css'%}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}">

	{% block references %}{% endblock %}
</head>

<body>

<div class="super_container">

	<!-- Header -->

	<header class="header trans_300">

		<!-- Main Navigation -->

		<div class="main_nav_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-right">
						<div class="logo_container">
							<img src="{% static 'images/logo8.jpeg'%}" class="img-thumbnail">
							<a href="{% url 'home' %}">Copren<span>LM</span></a>
						</div>
						<nav class="navbar">
							<ul class="navbar_menu">
								<li><a href="{% url 'home' %}">Inicio</a></li>
								<li><a href="{% url 'tienda' %}">Tienda</a></li>
								<li><a href="{% url 'tienda' %}">Contacto</a></li>
								<li><a href="{% url 'tienda' %}">Blog</a></li>
							</ul>
							<ul class="navbar_user">
								<li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
								<li class="checkout">
									<a href="{% url 'cart:cart_detail' %}">
										<i class="fa fa-shopping-cart" aria-hidden="true"></i>
										{% with total_items=cart|length %}
                							{% if cart|length > 0 %}
											<span id="checkout_items" class="checkout_items">{{ total_items }}</span>
											{% endif %}
										{% endwith %}
									</a>
								</li>
							</ul>
							<div class="hamburger_container">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

	<div class="fs_menu_overlay"></div>
	<div class="hamburger_menu">
		<div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
		<div class="hamburger_menu_content text-right">
			<ul class="menu_top_nav">
				<li class="menu_item"><a href="{% url 'home' %}">Inicio</a></li>
				<li class="menu_item"><a href="{% url 'tienda' %}">Tienda</a></li>
				<li class="menu_item"><a href="{% url 'tienda' %}">Contacto</a></li>
				<li class="menu_item"><a href="{% url 'tienda' %}">Blog</a></li>
			</ul>
		</div>
	</div>

	{% block contenidoPrincipal %}
	{% endblock %}
	<!-- Footer -->
	{% block footer %}
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
						<ul class="footer_nav">
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="#">Contáctanos</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
						<ul>
							<li><a href="https://www.facebook.com/manuel.guitierrezpalafox/?ref=br_rs" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="footer_nav_container">
						<div class="cr">©2018 Todos los derechos reservados. Esta demo fue realizada <i class="fa fa-heart-o" aria-hidden="true"></i> Por
						<a href="http://luckyware.mx">Luckyware</a></div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	{% endblock %}
</div>

<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static 'styles/bootstrap4/popper.js'%}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js'%}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{% static 'plugins/easing/easing.js'%}"></script>

{% block jsreferences %}
{% endblock %}
</body>

</html>

templates/detalleproducto.html
{% extends "basetienda.html" %}
{% load staticfiles %}

{% block pageTitle %} Detalle de producto{% endblock %}
{% block references %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css'%}" xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/single_styles.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/single_responsive.css'%}">
{% endblock %}


{% block contenidoPrincipal %}
<div class="super_container">

	<!-- Header -->

	<div class="fs_menu_overlay"></div>

	<!-- Hamburger Menu -->



	<div class="container single_product_container">

		<div class="row">
			<div class="col-lg-7">
				<div class="single_product_pics">
					<div class="row">
						<div class="col-lg-12 image_col order-lg-2 order-1">
							<div class="single_product_image">
								{% if product.image %}
								<div class="single_product_image_background" style="background-image:url({{ product.image.url }})"></div>
								{% else %}
								<div class="single_product_image_background" style="background-image:url(/static/images/no_image.png)"></div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-5">
				<div class="product_details">
					<div class="product_details_title">
						<h2>{{ product.name }}</h2>
						<p>{{ product.description|linebreaks }}</p>
					</div>
					<div class="original_price">$629.99 NO APLICA</div>
					<div class="product_price">{{ product.price }}MXN</div>
					<ul class="star_rating">
						<li><i class="fa fa-star" aria-hidden="true"></i></li>
						<li><i class="fa fa-star" aria-hidden="true"></i></li>
						<li><i class="fa fa-star" aria-hidden="true"></i></li>
						<li><i class="fa fa-star" aria-hidden="true"></i></li>
						<li><i class="fa fa-star-o" aria-hidden="true"></i></li>
					</ul>
					<div class="quantity d-flex flex-column flex-sm-row align-items-sm-center">
						<span>Número de artículos:</span>
						<div class="quantity_selector">
							<span class="minus"><i class="fa fa-minus" aria-hidden="true"></i></span>
							<span id="quantity_value">1</span>
							<span class="plus"><i class="fa fa-plus" aria-hidden="true"></i></span>
						</div>
							<form action="{% url "cart:cart_add" product.id %}" method="post" onsubmit="return setCantidadProducto(this);">
							{{ cart_product_form }}
            				{% csrf_token %}
							<div class="red_button add_to_cart_button"><input type="submit" value="Agregar al carro"></div>
							</form

					</div>
				</div>
			</div>
		</div>

	</div>

</div>
{% endblock %}

{% block jsreferences %}
<script src="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.js'%}"></script>
<script src="{% static 'js/single_custom.js'%}"></script>
{% endblock %}

templates/tienda.html
{% extends "basetienda.html" %}
{% load staticfiles %}

{% block pageTitle %} Tienda en línea {% endblock %}

{% block references %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/categories_styles.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/categories_responsive.css'%}">
{% endblock %}

{% block contenidoPrincipal %}
<div class="container product_section_container">
		<div class="row">
			<div class="col product_section clearfix">

				<!-- Sidebar -->

				<div class="sidebar">
					<div class="sidebar_section">
						<div class="sidebar_title">
							<h5>Categorías de los productos</h5>
						</div>
						<ul class="sidebar_categories">
							<li><a href="{% url 'tienda' %}">Todos los productos</a></li>
                             {% for c in categories %}
                                {% if category.slug == c.slug %}
                                    <li class="active"><a href="{{ c.get_absolute_url }}"><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>{{ c.name }}</a></li>
                                {% else %}
                                    <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>

                                {% endif %}
                            {% endfor %}


						</ul>
					</div>




				</div>

				<!-- Main Content -->

				<div class="main_content">

					<!-- Products -->

					<div class="products_iso">
						<div class="row">
							<div class="col">

								<!-- Product Sorting -->

								<div class="product_sorting_container product_sorting_container_top">
									<ul class="product_sorting">
										<li>
											<span class="type_sorting_text">Sin Ordenar</span>
											<i class="fa fa-angle-down"></i>
											<ul class="sorting_type">
												<li class="type_sorting_btn" data-isotope-option='{ "sortBy": "original-order" }'><span>Sin Ordenar</span></li>
												<li class="type_sorting_btn" data-isotope-option='{ "sortBy": "price" }'><span>Precio</span></li>
												<li class="type_sorting_btn" data-isotope-option='{ "sortBy": "name" }'><span>Nombre</span></li>
											</ul>
										</li>
										<li>
											<span>Mostrar</span>
											<span class="num_sorting_text">6</span>
											<i class="fa fa-angle-down"></i>
											<ul class="sorting_num">
												<li class="num_sorting_btn"><span>6</span></li>
												<li class="num_sorting_btn"><span>12</span></li>
												<li class="num_sorting_btn"><span>24</span></li>
											</ul>
										</li>
									</ul>

								</div>

								<!-- Product Grid -->

								<div class="product-grid">
									<!-- Product 1 -->
                                    {% for product in products %}
                                    <div class="product-item women">
										<div class="product product_filter">
											<div class="product_image">
												<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
											</div>
											<div class="favorite"></div>
											<div class="product_info">
												<h6 class="product_name"><a href="#">{{ product.name }}</a></h6>
												<div class="product_price">{{ product.price }} MXN</div>
											</div>
										</div>
										<div class="red_button add_to_cart_button"><a href="{{ product.get_absolute_url }}">Ver detalle</a></div>
									</div>
                                    {% endfor %}


								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}



{% block jsreferences %}
<script src="{% static 'plugins/jquery-ui-1.12.1.custom/jquery-ui.js'%}"></script>
<script src="{% static 'js/categories_custom.js'%}"></script>
{% endblock %}